### ISSUE TITLE
req: add this workflow

### ISSUE THREAD

**Issue by fxjkhr** [vitorgalvao/requested-alfred-workflows#1]
Hi, 

Not sure if this is the approprite method to request additions to your repo, but the workflow shared here https://www.alfredforum.com/topic/11424-how-do-i-call-for-the-icloud-drive-folder/?tab=comments#comment-62085 could use a home on the repo.

**Comment by vitorgalvao** [comment]
Thank you for the interest, but this repo is for Workflows that I made to help the community. Supporting other people’s Workflows wouldn’t make sense. Not only is it something I can’t do (the code isn’t mine), it’s something I don’t want to do (I don’t want to take responsibility for malicious actors, or for keeping their code alive and linked correctly).
